server:
  port: 8080

spring:
  application:
    name: organization-management

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.show_sql: true
    open-in-view: false

  flyway:
    locations:
      - classpath:db/{vendor}/common

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_JDBC_URI}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth2.serverBaseUrl}/${oauth2.serverJwkSetUri}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

oauth2:
  serverBaseUrl: ${KC_BASE_URL}
  realm: ${KC_REALM}
  serverJwkSetUri: realms/${oauth2.realm}/protocol/openid-connect/certs
  adminClientId: ${KC_ADMIN_CLIENT}
  adminClientSecret: ${KC_ADMIN_CLIENT_SECRET}

interactive:
  exchange: 'app.updates'
  queue: 'upd'
  routing-key: 'updates.#'
