server:
  port: 8080

spring:
  application:
    name: organization-management

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.show_sql: true
    open-in-view: false

  flyway:
    locations:
      - classpath:db/{vendor}/common

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_JDBC_URI}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWK_SET_URI}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
